export { default as Header } from './Header'
export { default as Footer } from './Footer'
export { default as Image } from './Image'
export { default as Cursor } from './Cursor'
export { default as Modal } from './Modal'
